import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Form from '../components/Form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LeetCoin Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>LeetCoin Calculator</h1>
      <Form/>
    </div>
  )
}
